<?php

namespace Database\Seeders;

use App\Models\Kegiatan\ProgramKegiatan;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProgramKegiatanSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {


        $data = [
            0 => [
                'tahun_anggaran' => '2022',
                'type' => 'program',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '02',
                'nomenklatur' => 'PROGRAM PERENCANAAN LINGKUNGAN HIDUP',
            ],
            1 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 1 ',
                'type' => 'kegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '02',
                'kode_kegiatan' => '2.01',
                'nomenklatur' => 'Rencana Perlindungan dan Pengelolaan Lingkungan Hidup (RPPLH) Kabupaten/Kota',
            ],
            2 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 1 ',
                'id_kegiatan' => ' 2 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '02',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '01',
                'nomenklatur' => 'Penyusunan dan Penetapan RPPLH Kabupaten/Kota',
                'kinerja' => 'Tersusunnya RPPLH Kabupaten/ Kota',
                'indikator' => 'Jumlah Muatan Hasil Penyusunan dan Penetapan RPPLH Kabupaten/ Kota yang Disusun',
                'satuan' => 'Dokumen',
            ],
            3 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 1 ',
                'id_kegiatan' => ' 2 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '02',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '02',
                'nomenklatur' => 'Pengendalian Pelaksanaan RPPLH Kabupaten/Kota',
                'kinerja' => 'Tersedianya Dokumen Telaahan Kebijakan yang Telah Mengakomodir RPPLH Kabupaten/Kota',
                'indikator' => 'Jumlah Dokumen Telaahan Kebijakan yang Telah Mengakomodir RPPLH Kabupaten/Kota',
                'satuan' => 'Dokumen',
            ],
            4 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 1 ',
                'type' => 'kegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '02',
                'kode_kegiatan' => '2.02',
                'nomenklatur' => 'Penyelenggaraan Kajian Lingkungan Hidup Strategis (KLHS) Kabupaten/Kota',
            ],
            5 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 1 ',
                'id_kegiatan' => ' 5 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '02',
                'kode_kegiatan' => '2.02',
                'kode_sub_kegiatan' => '01',
                'nomenklatur' => 'Pembuatan dan Pelaksanaan KLHS Rencana Tata Ruang',
                'kinerja' => 'Tersusunnya KLHS Rencana Tata Ruang Kabupaten/Kota',
                'indikator' => 'Jumlah Dokumen KLHS Rencana Tata Ruang Kabupaten/Kota yang Disusun',
                'satuan' => 'Dokumen',
            ],
            6 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 1 ',
                'id_kegiatan' => ' 5 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '02',
                'kode_kegiatan' => '2.02',
                'kode_sub_kegiatan' => '02',
                'nomenklatur' => 'Pembuatan dan Pelaksanaan KLHS RPJPD/RPJMD',
                'kinerja' => 'Tersusunnya KLHS RPJPD/ RPJMD Kabupaten/Kota',
                'indikator' => 'Jumlah Dokumen KLHS RPJPD/ RPJMD Kabupaten/Kota pang Disusun',
                'satuan' => 'Dokumen',
            ],
            7 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 1 ',
                'id_kegiatan' => ' 5 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '02',
                'kode_kegiatan' => '2.02',
                'kode_sub_kegiatan' => '03',
                'nomenklatur' => 'Pembuatan dan Pelaksanaan KLHS untuk KRP yang Berpotensi Menimbulkan Dampak/Resiko Lingkungan Hidup',
                'kinerja' => 'Tersusunnya KLHS untuk KRP Kabupaten/Kota yang Berpotensi Menimbulkan Dampak/Resiko Lingkungan Hidup',
                'indikator' => 'Jumlah Dokumen KLHS KRP Kabupaten/Kota yang Berpotensi Menimbulkan Dampak/Resiko Lingkungan Hidup yang Disusun',
                'satuan' => 'Dokumen',
            ],
            8 => [
                'tahun_anggaran' => '2022',
                'type' => 'program',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '03',
                'nomenklatur' => 'PROGRAM PENGENDALIAN PENCEMARAN DAN/ATAU KKRUSAKAN LINGKUNGAN HIDUP',
            ],
            9 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 9 ',
                'type' => 'kegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '03',
                'kode_kegiatan' => '2.01',
                'nomenklatur' => 'Pencegahan Pencemaran dan/atau Kerusakan Lingkungan Hidup Kabupaten/ Kota',
            ],
            10 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 9 ',
                'id_kegiatan' => ' 10 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '03',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '01',
                'nomenklatur' => 'Koordinasi, Sinkronisasi, dan Pelaksanaan Pencegahan Pencemaran Lingkungan Hidup Dilaksanakan Terhadap Media Tanah, Air, Udara, dan Laut',
                'kinerja' => 'Tersusunnya Dokumen Uji Kualitas Lingkungan Hidup Dilaksanakan Terhadap Media Tanah, Air, Udara, dan Laut',
                'indikator' => 'Jumlah Dokumen Uji Kualitas Lingkungan Hidup Dilaksanakan Terhadap Media Tanah, Air, Udara, dan Laut',
                'satuan' => 'Dokumen',
            ],
            11 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 9 ',
                'id_kegiatan' => ' 10 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '03',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '02',
                'nomenklatur' => 'Koordinasi, Sinkronisasi dan Pelaksanaan Pengendalian Emisi Gas Rumah Kaca, Mitigasi dan Adaptasi Perubahan Iklim',
                'kinerja' => 'Terlaksananya Koordinasi, Sinkronisasi dan Pelaksanaan Pengendalian Emisi Gas Rumah Kaca, Mitigasi dan Adaptasi Perubahan Iklim',
                'indikator' => 'Jumlah Dokumen Hasil Koordinasi dan Sinkronisasi Inventarisasi Gas Rumah Kaca dari Sektor Lingkungan Hidup yang Dilaksanakan',
                'satuan' => 'Dokumen',
            ],
            12 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 9 ',
                'id_kegiatan' => ' 10 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '03',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '03',
                'nomenklatur' => 'Pengelolaan Laboratorium Lingkungan Hidup Kabupaten/Kota',
                'kinerja' => 'Terlaksananya Pengambilan Contoh U”1, Pengujian Parameter Kualitas Lingkungan dan Dokumen Mutu yang Dilaksanakan',
                'indikator' => 'Jumlah Pengambilan Contoh U”1, Pengujian Parameter Kualitas Lingkungan dan Dokumen Mutu yang Dilaksanakan',
                'satuan' => 'Dokumen',
            ],
            13 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 9 ',
                'type' => 'kegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '03',
                'kode_kegiatan' => '2.02',
                'kode_sub_kegiatan' => '',
                'nomenklatur' => 'Penanggulangan Pencemaran dan/atau Kerusakan Lingkungan Hidup Kabupaten/ Kota',
            ],
            14 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 9 ',
                'id_kegiatan' => ' 14 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '03',
                'kode_kegiatan' => '2.02',
                'kode_sub_kegiatan' => '01',
                'nomenklatur' => 'Pemberian Informasi Peringatan Pencemaran dan/atau Kerusakan Lingkungan Hidup pada Masyarakat',
                'kinerja' => 'Terlaksananya Sosialisasi Informasi Peringatan Pencemaran dan/atau Kerusakan Lingkungan Hidup pada Masyarakat di Kabupaten/Kota',
                'indikator' => 'Jumlah Laporan Sosialisasi Informasi Peringatan Pencemaran dan/ atau Kerusakan Lingkungan Hidup pada Masyarakat di Kabupaten/ Kota yang Dilaksanakan',
                'satuan' => 'Laporan',
            ],
            15 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 9 ',
                'id_kegiatan' => ' 14 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '03',
                'kode_kegiatan' => '2.02',
                'kode_sub_kegiatan' => '02',
                'nomenklatur' => 'Pengisolasian Pencemaran dan/ atau Kerusakan Lingkungan Hidup',
                'kinerja' => 'Area Pencemaran dan/atau Kerusakan Lingkungan Hidup yang Diisolasi',
                'indikator' => 'Jumlah Lokasi Pencemaran dan/ atau Kerusakan Lingkungan Hidup yang Diisolasi',
                'satuan' => 'Lokasi',
            ],
            16 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 9 ',
                'id_kegiatan' => ' 14 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '03',
                'kode_kegiatan' => '2.02',
                'kode_sub_kegiatan' => '03',
                'nomenklatur' => 'Penghentian Pencemaran dan/atau Kerusakan Lingkungan Hidup',
                'kinerja' => 'Sumber Pencemaran dan/atau Kerusakan Lingkungan Hidup yang Dihentikan',
                'indikator' => 'Jumlah Sumber Pencemar dan/atau Kerusakan Lingkungan Hidup yang Dihentikan',
                'satuan' => 'Titik',
            ],
            17 => [
                'tahun_anggaran' => '2022',
                'type' => 'program',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '03',
                'kode_kegiatan' => '2.03',
                'kode_sub_kegiatan' => '',
                'nomenklatur' => 'Pemulihan Pencemaran dan/ atau Kerusakan Lingkungan Hidup Kabupaten/Kota',
            ],
            18 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 18 ',
                'id_kegiatan' => ' 18 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '03',
                'kode_kegiatan' => '2.03',
                'kode_sub_kegiatan' => '01',
                'nomenklatur' => 'Koordinasi dan Sinkronisasi Penghentian Sumber Pencemaran',
                'kinerja' => 'Terlaksananya Koordinasi dan Sinkronisasi Penghentian Pencemaran dan/atau Kerusakan Lingkungan Hidup Kewenangan Pemerintah dan/atau Provinsi',
                'indikator' => 'Jumlah Dokumen Hasil Koordinasi dan Sinkronisasi Penghentian Sumber Pencemaran Kewenangan Pemerintah dan/atau Provinsi dan/atau Sektor Lain hingga Terhentinya Sumber Pencemaran yang Dilaksanakan',
                'satuan' => 'Dokumen',
            ],
            19 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 9 ',
                'type' => 'kegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '03',
                'kode_kegiatan' => '2.03',
                'kode_sub_kegiatan' => '02',
                'nomenklatur' => 'Koordinasi dan Sinkronisasi Pembersihan Unsur Pencemar',
                'kinerja' => 'Terlaksananya Koordinasi dan Sinkronisasi Pembersihan Unsur Pencemar',
                'indikator' => 'Jumlah Dokumen Hasil Koordinasi dan Sinkronisasi Pembersihan Unsur Pencemar',
                'satuan' => 'Dokumen',
            ],
            20 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 9 ',
                'id_kegiatan' => ' 20 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '03',
                'kode_kegiatan' => '2.03',
                'kode_sub_kegiatan' => '03',
                'nomenklatur' => 'Koordinasi, Sinkronisasi dan Pelaksanaan Remediasi',
                'kinerja' => 'Terlaksananya Koordinasi, Sinkronisasi dan Pelaksanaan Remediasi',
                'indikator' => 'Jumlah Dokumen Hasil Koordinasi, Sinkronisasi dan Pelaksanaan Remediasi',
                'satuan' => 'Dokumen',
            ],
            21 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 9 ',
                'id_kegiatan' => ' 20 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '03',
                'kode_kegiatan' => '2.03',
                'kode_sub_kegiatan' => '04',
                'nomenklatur' => 'Koordinasi, Sinkronisasi dan Pelaksanaan Rehabilitasi',
                'kinerja' => 'Terlaksananya Koordinasi, Sinkronisasi dan Pelaksanaan Rehabilitasi',
                'indikator' => 'Jumlah Dokumen Hasil Koordinasi, Sinkronisasi dan Pelaksanaan Rehabilitasi',
                'satuan' => 'Dokumen',
            ],
            22 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 9 ',
                'id_kegiatan' => ' 20 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '03',
                'kode_kegiatan' => '2.03',
                'kode_sub_kegiatan' => '05',
                'nomenklatur' => 'Koordinasi, Sinkronisasi dan Pelaksanaan Restorasi',
                'kinerja' => 'Terlaksananya Koordinasi, Sinkronisasi dan Pelaksanaan Restorasi',
                'indikator' => 'Jumlah Dokumen Hasil Koordinasi, Sinkronisasi dan Pelaksanaan Restorasi',
                'satuan' => 'Dokumen',
            ],
            23 => [
                'tahun_anggaran' => '2022',
                'type' => 'program',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '04',
                'kode_sub_kegiatan' => '',
                'nomenklatur' => 'PROGRAM PENGELOLAAN KEANEKARAGAMAN HAYATI (KEHATI)',
            ],
            24 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 24 ',
                'type' => 'kegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '04',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '',
                'nomenklatur' => 'Pengelolaan Keanekaragaman Hayati Kabupaten/Kota',
            ],
            25 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 24 ',
                'id_kegiatan' => ' 25 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '04',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '01',
                'nomenklatur' => 'Penyusunan dan Penetapan Rencana Pengelolaan Keanekaragaman Hayati',
                'kinerja' => 'Rencana Induk Pengelolaan Keanekaragaman Hayati yang Disusun',
                'indikator' => 'Jumlah Dokumen Rencana Induk Pengelolaan Kehati yang Disusun',
                'satuan' => 'Dokumen',
            ],
            26 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 24 ',
                'id_kegiatan' => ' 25 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '04',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '02',
                'nomenklatur' => 'Pengelolaan Taman Keanekaragaman Hayati di Luar Kawasan Hutan',
                'kinerja' => 'Taman Keanekaragaman Hayati di Luar Kawasan Hutan yang Dikelola',
                'indikator' => 'Luas Taman Kehati Di Luar Kawasan Hutan yang Dikelola Lingkup Kewenangan Kabupaten/ Kota',
                'satuan' => 'Ha',
            ],
            27 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 24 ',
                'id_kegiatan' => ' 25 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '04',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '03',
                'nomenklatur' => 'Pengelolaan Kebun Raya',
                'kinerja' => 'Kebun Raya yang Dikelola',
                'indikator' => 'Luas Kebun Raya yang Dikelola Lingkup Kewenangan Kabupaten/Kota',
                'satuan' => 'Ha',
            ],
            28 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 24 ',
                'id_kegiatan' => ' 25 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '04',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '04',
                'nomenklatur' => 'Pengelolaan Ruang Terbuka Hijau (RTH)',
                'kinerja' => 'Ruang Terbuka Hijau (RTH) yang Dikelola',
                'indikator' => 'Luas RTH yang Dikelola Lingkup Kewenangan Kabupaten/Kota',
                'satuan' => 'Ha',
            ],
            29 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 24 ',
                'id_kegiatan' => ' 25 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '04',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '05',
                'nomenklatur' => 'Pengelolaan Taman Keanekaragaman Hayati Lairınya',
                'kinerja' => 'Taman Keanekaragaman Hayati Lainnya yang Dikelola',
                'indikator' => 'Luas Taman KKHATI Lainnya yang Dikelola Lingkup Kewenangan Kabupaten/ Kota',
                'satuan' => 'Ha',
            ],
            30 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 24 ',
                'id_kegiatan' => ' 25 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '04',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '06',
                'nomenklatur' => 'Pengembangan Kapasitas Kelembagaan dan SDM dalam Pengelolaan Keanekaragaman Hayati',
                'kinerja' => 'Meningkatnya Jumlah Orang yang Meningkat Kapasitasnya dalam Pengelolaan Keanekaragaman Hayati',
                'indikator' => 'Jumlah Orang yang Meningkat Kapasitasnya dalam Pengelolaan Keanekaragaman Hayati',
                'satuan' => 'Or 8',
            ],
            31 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 24 ',
                'id_kegiatan' => ' 25 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '04',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '07',
                'nomenklatur' => 'Pengelolaan Sarana dan Prasarana Keanekaragaman Hayati',
                'kinerja' => 'Sarana dan Prasarana Keanekaragam Hayati yang Dikelola',
                'indikator' => 'Jumlah Sarana dan Prasarana Keanekaragaman Hayati yang Dikelola',
                'satuan' => 'Unit',
            ],
            32 => [
                'tahun_anggaran' => '2022',
                'type' => 'program',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '05',
                'kode_sub_kegiatan' => '',
                'nomenklatur' => 'PROGRAM PENGENDALIAN BAHAN BERBAHAYA DAN BERACUN (B3) DAN LIMBAH BAHAN BERBAHAYA DAN BERACUN (LIMBAH B3}',
            ],
            33 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 33 ',
                'type' => 'kegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '05',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '',
                'nomenklatur' => 'Penyimpanan sementara Limbah B3',
            ],
            34 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 33 ',
                'id_kegiatan' => ' 34 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '05',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '01',
                'nomenklatur' => 'Fasilitasi Pemenuhan Komitmen Izin Penyimpanan sementara Limbah B3 Dilaksanakan Melalui Sistem Pelayanan Perizinan Berusaha Terintegrasi Secara Elektronik',
                'kinerja' => 'Terfasilitasinya Pemenuhan Komitmen Izin Penyimpanan sementara Limbah B3 Dilaksanakan Melalui Sistem Pelayanan Perizinan Berusaha Terintegrasi Secara Elektronik',
                'indikator' => 'Jumlah Fasilitasi Persetujuan/Izin Penyimpanan sementara Limbah B3 yang Dilaksanakan Melalui Sistem Pelayanan Perizinan Berusaha Terintegrasi Secara Elektronik',
                'satuan' => 'Dokumen',
            ],
            35 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 33 ',
                'id_kegiatan' => ' 34 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '05',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '02',
                'nomenklatur' => 'Verifikasi Lapangan untuk Memastikan Pemenuhan Persyaratan Administrasi dan Teknis Penyimpanan sementara Limbah B3',
                'kinerja' => 'Terlaksananya Verifikasi Lapangan untuk Memastikan Pemenuhan Persyaratan Administrasi dan Teknis Penyimpanan sementara dan Pengumpulan Limbah B3',
                'indikator' => 'Jumlah Laporan Kegiatan Verifıkasi Lapangan Pemenuhan Komitmen Persetujuan/Izin Penyimpanan sementara dan Pengumpulan Limbah B3',
                'satuan' => 'Laporan',
            ],
            36 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 33 ',
                'type' => 'kegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '05',
                'kode_kegiatan' => '2.02',
                'kode_sub_kegiatan' => '',
                'nomenklatur' => 'Pengumpulan Limbah B3 dalam 1 (Satu) Daerah Kabupaten/Kota',
            ],
            37 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 33 ',
                'id_kegiatan' => ' 37 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '05',
                'kode_kegiatan' => '2.02',
                'kode_sub_kegiatan' => '01',
                'nomenklatur' => 'Fasilitasi Pemenuhan Komitmen Izin Pengumpulan Limbah B3 Dilaksanakan Melalui Sistem Pelayanan Perizinan Berusaha Terintegrasi Secara Elektronik',
                'kinerja' => 'Terfasilitasinya Pemenuhan Komitmen Izin Pengumpulan Limbah B3 Dilaksanakan Melalui Sistem Pelayanan Perizinan Berusaha Terintegrasi Secara Elektronik',
                'indikator' => 'Jumlah Fasilitasi Persetujuan/Izin Pengumpulan Limbah B3 yang Dilaksanakan Melalui Sistem Pelayanan Perizinan Berusaha Terintegrasi Secara Elektronik',
                'satuan' => 'Dokumen',
            ],
            38 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 33 ',
                'id_kegiatan' => ' 37 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '05',
                'kode_kegiatan' => '2.02',
                'kode_sub_kegiatan' => '02',
                'nomenklatur' => 'Koordinasi dan Sinkronisasi Pengelolaan Limbah B3 dengan Pemerintah Provinsi dalam rangka Pengangkutan, Pemanfaatan, Pengolahan, dan/atau Penimbunan',
                'kinerja' => 'Terlaksananya Koordinasi dan Sinkronisasi Terkait Pengelolaan Limbah B3 dalam rangka Pengangkutan, Pemanfaatan, Pengolahan, dan/atau Penimbunan yang Bukan Menjadi Kewenangan Pemerintah Daerah Kabupaten/Kota serta Pelaksanaan Pengumpulan dan Penyimpanan sementara Limbah B3 yang Sesuai dengan Kewenangannya',
                'indikator' => 'Jumlah Dokumen Hasil Koordinasi & Sinkronisasi Pengelolaan Limbah B3 dengan Pemerintah dan Pemerintah Provinsi dalam rangka Pengangkutan, Pemanfaatan, Pengolahan, dan/ atau Penimbunan yang Bukan Menjadi Kewenangan Pemda Kabupaten/ Kota serta Pelaksanaan Pengumpulan dan Penyimpanan sementara Limbah B3 yang Sesuai dengan Kewenangannya',
                'satuan' => 'Dokumen',
            ],
            39 => [
                'tahun_anggaran' => '2022',
                'type' => 'program',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '06',
                'nomenklatur' => 'PROGRAM PEMBINAAN DAN PENGAWASAN TERHADAP IZIN LINGKUNGAN DAN IZIN PERLINDUNGAN DAN PENGELOLAAN LINGKUNGAN HIDUP (PPLH)',
            ],
            40 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 40 ',
                'type' => 'kegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '06',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '',
                'nomenklatur' => 'Pembinaan dan Pengawasan Terhadap Usaha dan/atau Kegiatan yang Izin Lingkungan dan Izin PPLH Diterbitkan oleh Pemerintah Daerah Kabupaten/Kota',
            ],
            41 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 40 ',
                'id_kegiatan' => ' 41 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '06',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '01',
                'nomenklatur' => 'Fasilitasi Pemenuhan Ketentuan dan Kewajiban Izin Lingkungan dan/atau Izin PPLH',
                'kinerja' => 'Kegiatan Fasilitasi Rekomendasi dan/atau Pemenuhan Ketentuan Persetujuan Teknis, Persetujuan Lingkungan, dan Surat Kelayakan Operasi yang Diberikan',
                'indikator' => 'Jumlah Rekomendasi dan/atau Persetujuan Teknis, Persetujuan Lingkungan, dan Surat Kelayakan Operasi yang Diberikan',
                'satuan' => 'Dokumen',
            ],
            42 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 40 ',
                'id_kegiatan' => ' 41 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '06',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '02',
                'nomenklatur' => 'Pengembangan Kapasitas Pejabat Pengawas Lingkungan Hidup',
                'kinerja' => 'Kegiatan Fasilitasi Rekomendasi dan/atau Pemenuhan Ketentuan Persetujuan Teknis, Persetujuan Lingkungan, dan Surat Kelayakan Operasi yang Diberikan',
                'indikator' => 'Jumlah Rekomendasi dan/atau Persetujuan Teknis, Persetujuan Lingkungan, dan Surat Kelayakan Operasi yang Diberikan',
                'satuan' => 'Orang',
            ],
            43 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 40 ',
                'id_kegiatan' => ' 41 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '06',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '03',
                'nomenklatur' => 'Pengawasan Usaha dan/atau Kegiatan yang Izin Lingkungan Hidup, Izin PPLH yang Diterbitkan oleh Pemerintah Daerah Kabupaten/Kota',
                'kinerja' => 'Meningkatnya Pengawasan Terhadap Usaha dan/atau Kegiatan yang Izin Lingkungan, Persetujuan Lingkungan, Surat Kelayakan Operasi Diterbitkan oleh Pemerintah Daerah Kabupaten/Kota',
                'indikator' => 'Jumlah Laporan Dari Usaha dan/atau Kegiatan yang Diawasi Izin Lingkungan, Persetujuan Lingkungan, Surat Kelayakan Operasi oleh Pemerintah Daerah Kabupaten/Kota',
                'satuan' => 'Laporan',
            ],
            44 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 40 ',
                'id_kegiatan' => ' 41 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '06',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '04',
                'nomenklatur' => 'Koordinasi dan Sinkronisasi Pengawasan dan Penerapan Sanksi Upaya dan Rencana PPLH',
                'kinerja' => 'Terlaksananya Koordinasi dan Sinkronisasi Pengawasan dan Penerapan Sanksi Upaya dan Rencana PPLH',
                'indikator' => 'Jumlah Dokumen Hasil Koordinasi dan Sinkronisasi Pengawasan dan Penerapan Sanksi Upaya dan Rencana PPLHD',
                'satuan' => 'Dokumen',
            ],
            45 => [
                'tahun_anggaran' => '2022',
                'type' => 'program',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '07',
                'kode_sub_kegiatan' => '',
                'nomenklatur' => 'PROGRAM PENGAKUAN KEBERADAAN MASYARAKAT HUKUM ADAT (MHA), KEARIFAN LOKAL DAN HAK MHA YANG TERKAIT DENGAN PPLH',
            ],
            46 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 46 ',
                'type' => 'kegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '07',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '',
                'nomenklatur' => 'Pengakuan MHA, Kearifan Lokal, Pengetahuan Tradisional, dan Hak MHA yang Terkait dengan PPLH',
            ],
            47 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 46 ',
                'id_kegiatan' => ' 47 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '07',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '01',
                'nomenklatur' => 'Koordinasi, Sinkronisasi, Penyediaan Data, dan Informasi Pengakuan Keberadaan MHA Kearifan Lokal atau Pengetahuan Tradisional dan Hak Kearifan Lokal atau Pengetahuan Tradisional dan Hak MHA Terkait dengan PPLH',
                'kinerja' => 'Terlaksananya Koordinasi, Sinkronisasi, Penyediaan Data dan Informasi Pengakuan Keberadaan MHA Kearifan Lokal atau Pengetahuan Tradisional dan Hak Kearifan Lokal atau Pengetahuan Tradisional dan Hak MHA Terkait dengan PPLH',
                'indikator' => 'Jumlah Dokumen Hasil Koordinasi, Sinkronisasi, Penyediaan Data dan Informasi Pengakuan Keberadaan MHA Kearifan Lokal atau Pengetahuan Tradisional dan Hak Kearifan Lokal atau Pengetahuan Tradisional dan Hak MHA Terkait dengan PPLH',
                'satuan' => 'Dokumen',
            ],
            48 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 46 ',
                'type' => 'kegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '07',
                'kode_kegiatan' => '2.02',
                'kode_sub_kegiatan' => '',
                'nomenklatur' => 'Peningkatan Kapasitas MHA dan Kearifan Lokal, Pengetahuan Tradisional dan Hak MHA yang Terkait dengan PPLH',
            ],
            49 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 46 ',
                'id_kegiatan' => ' 49 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '07',
                'kode_kegiatan' => '2.02',
                'kode_sub_kegiatan' => '01',
                'nomenklatur' => 'Pemberdayaan, Kemitraan, Pendampingan, dan Penguatan Kelembagaan MHA, Kearifan Lokal, Pengetahuan Tradisional, dan Hak MHA Terkait dengan PPLH',
                'kinerja' => 'Kelembagaan MHA, Kearifan Lokal, Pengetahuan Tradisional dan Hak MHA Terkait dengan PPLH yang Dilakukan Pemberdayaan, Kemitraan, Pendampingan dan Penguatan',
                'indikator' => 'Jumlah Dokumen Kelembagaan MHA, Kearifan Lokal, Pengetahuan Tradisional dan Hak MHA Terkait dengan PPLH yang Dilakukan Pemberdayaan, Kemitraan, Pendampingan dan Penguatan',
                'satuan' => 'Dokumen',
            ],
            50 => [
                'tahun_anggaran' => '2022',
                'type' => 'program',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '08',
                'nomenklatur' => 'PROGRAM PENINGKATAN PENDIDIKAN, PELATIHAN DAN PENYULUHAN LINGKUNGAN HIDUP UNTUK MASYARAKAT',
            ],
            51 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 51 ',
                'type' => 'kegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '08',
                'kode_kegiatan' => '2.01',
                'nomenklatur' => 'Penyelenggaraan Pendidikan, Pelatihan, dan Penyuluhan Lingkungan Hidup untuk Lembaga Kemasyarakatan Tingkat Daerah Kabupaten/Kota',
            ],
            52 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 51 ',
                'id_kegiatan' => ' 52 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '08',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '01',
                'nomenklatur' => 'Peningkatan Kapasitas dan Kompetensi Sumber Daya Manusia Bidang Lingkungan Hidup untuk Lembaga Kemasyarakatan',
                'kinerja' => 'Meningkatnya Jumlah Lembaga Kemasyarakatan/ Kelompok Masyarakat/lnstitusi Skala Kabupaten/Kota dan/atau yang Terdaftar di Kabupaten/Kota yang Ditingkatkan Kapasitas dan Kompetensi SDMnya',
                'indikator' => 'Jumlah  Lembaga/kelompok Masyarakat/lnstitusi yang Terdaftar yang Meningkat Kapasitas dan Kompetensinya Terkait PPLH',
                'satuan' => 'Lembaga',
            ],
            53 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 51 ',
                'id_kegiatan' => ' 52 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '08',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '02',
                'nomenklatur' => 'Pendampingan Gerakan Peduli Lingkungan Hidup',
                'kinerja' => 'Terlaksananya Pendampingan Pembinaan Gerakan Peduli dan Berbudaya Lingkungan Hidup',
                'indikator' => 'Jumlah Pendampingan Pembinaan Gerakan Peduli dan Berbudaya Lingkungan Hidup yang Dilaksanakan',
                'satuan' => 'Dokumen',
            ],
            54 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 51 ',
                'id_kegiatan' => ' 52 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '08',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '03',
                'nomenklatur' => 'Penyelenggaraan Penyuluhan dan Kampanye Lingkungan Hidup',
                'kinerja' => 'Meningkatnya Jumlah Penyuluhan dan Kampanye Lingkungan Hidup Tingkat Daerah Kabupaten/ Kota',
                'indikator' => 'Jumlah  Masyarakat/Kelompok Masyarakat/Pelaku Usaha/Kegiatan yang terlibat',
                'satuan' => 'Orang',
            ],
            55 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 51 ',
                'id_kegiatan' => ' 52 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '08',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '04',
                'nomenklatur' => 'Penumbuhan Kesadaran Keluarga dalam Peningkatan Kualitas Lin kungan Hidup dan Kawasan Pemukiman yang Sehat',
                'kinerja' => 'Terlaksananya Penumbuhan Kesadaran Keluarga dalam Peningkatan Kualitas Lingkungan Hidup dan Kawasan Pemukiman yang Sehat',
                'indikator' => 'Jumlah Keluarga yang Mengikuti Penumbuhan Kesadaran Keluarga dalam Peningkatan Kualitas Lingkungan Hidup dan Kawasan Pemukiman yang Sehat',
                'satuan' => 'Keluarga',
            ],
            56 => [
                'tahun_anggaran' => '2022',
                'type' => 'program',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '09',
                'nomenklatur' => 'PROGRAM PENGHARGAAN LINGKUNGAN HIDUP UNTUK MASYARAKAT',
            ],
            57 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 57 ',
                'type' => 'kegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '09',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '',
                'nomenklatur' => 'Pemberian Penghargaan Lingkungan Hidup Tingkat Daerah Kabupaten/Kota',
            ],
            58 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 57 ',
                'id_kegiatan' => ' 58 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '09',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '01',
                'nomenklatur' => 'Penilaian Kinerja Masyarakat/Lembaga Masyarakat/Dunia Usaha/Dunia Pendidikan/ Filantropi dalam Perlindungan dan Pengelolaan Lingkungan Hidup',
                'kinerja' => 'Terlaksananya Penilaian Kinerja Masyarakat/Lembaga Masyarakat/Dunia Usaha/Dunia Pendidikan/Filantropi dalam Perlindungan dan Pengelolaan Lingkungan Hidup',
                'indikator' => 'Jumlah Masyarakat/Lembaga Masyarakat/Dunia Usaha/Dunia Pendidikan/ Filantrophi yang Dinilai Kiner’an a dalam rangka PPLH',
                'satuan' => 'Entitas',
            ],
            59 => [
                'tahun_anggaran' => '2022',
                'type' => 'program',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '10',
                'nomenklatur' => 'PROGRAM PENANGANAN PENGADUAN LINGKUNGAN HIDUP',
            ],
            60 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 60 ',
                'type' => 'kegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '10',
                'kode_kegiatan' => '2.01',
                'nomenklatur' => 'Penyelesaian Pengaduan Masyarakat di Bidang Perlindungan dan Pengelolaan Lingkungan Hidup (PPLH) Kabupaten / Kota',
            ],
            61 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 60 ',
                'id_kegiatan' => ' 61 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '10',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '01',
                'nomenklatur' => 'Pengelolaan Pengaduan Masyarakat Terhadap PPLH Kabupaten/Kota',
                'kinerja' => 'Pengaduan Masyarakat Terhadap PPLH Kabupaten/ Kota yang Dikelola',
                'indikator' => 'Jumlah Pengaduan Masyarakat Terhadap PPLH Kabupaten/Kota yang Ditindaklanjuti/Ditangani',
                'satuan' => 'Dokumen',
            ],
            62 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 60 ',
                'id_kegiatan' => ' 61 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '10',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '02',
                'nomenklatur' => 'Koordinasi dan Sinkronisasi Penerapan Sanksi Administrasi, Penyelesaian Sengketa, dan/atau Penyidikan Lingkungan Hidup di Luar Pengadilan atau Melalui Pengadilan',
                'kinerja' => 'Terlaksananya Koordinasi dan Sinkronisasi Penerapan Sanksi Administrasi, Penyelesaian Sengketa, dan/atau Penyidikan Lingkungan Hidup di Luar Pengadilan atau Melalui Pengadilan',
                'indikator' => 'Jumlah Dokumen Hasil Koordinasi dan Sinkronisasi Penerapan Sanksi Administrasi, Penyelesaian Sengketa, dan/atau Penyidikan Lingkungan Hidup di Luar Pengadilan atau Melalui Pengadilan',
                'satuan' => 'Dokumen',
            ],
            63 => [
                'tahun_anggaran' => '2022',
                'type' => 'program',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '11',
                'kode_sub_kegiatan' => '',
                'nomenklatur' => 'PROGRAM PENGELOLAAN PERSAMPAHAN',
            ],
            64 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 64 ',
                'type' => 'kegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '11',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '',
                'nomenklatur' => 'Pengelolaan Sampah',
            ],
            65 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 64 ',
                'id_kegiatan' => ' 65 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '11',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '01',
                'nomenklatur' => 'Penyusunan Kebijakan dan Strategi Daerah Pengelolaan Sampah Kabupaten/ Kota',
                'kinerja' => 'Tersusunnya Kebijakan dan Strategi Daerah Pengelolaan Sampah Kabupaten/Kota',
                'indikator' => 'Jumlah Dokumen Kebijakan dan Strategi Daerah Pengelolaan Sampah Kabupaten/Kota yang Disusun dan Ditetapkan',
                'satuan' => 'Dokumen',
            ],
            66 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 64 ',
                'id_kegiatan' => ' 65 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '11',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '02',
                'nomenklatur' => 'Pengurangan Sampah dengan Melakukan Pembatasan, Pendauran Ulang dan Pemanfaatan Kembali',
                'kinerja' => 'Telaksananya Pengurangan Sampah dengan Melakukan Pembatasan, Pendauran Ulang dan Pemanfaatan Kembali',
                'indikator' => 'Jumlah Laporan Hasil Pengurangan Sampah dengan Melakukan Pembatasan, Pendauran Ulang dan Pemanfaatan Kembali',
                'satuan' => 'Laporan',
            ],
            67 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 64 ',
                'id_kegiatan' => ' 65 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '11',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '03',
                'nomenklatur' => 'Penanganan Sampah dengan Melakukan Pemilahan, Pengumpulan, Pengangkutan, Pengolahan, dan Pemrosesan Akhir Sampah di TPA/TPST/ SPA Kabupaten/Kota',
                'kinerja' => 'Terlaksananya Penanganan Sampah dengan Melakukan Pemilahan, Pengumpulan, Pengangkutan, Pengolahan, dan Pemrosesan Akhir Sampah di TPA/TPST/SPA Kabupaten/Kota',
                'indikator' => 'Jumlah Sampah yang Dipilah, Dikumpulkan, Diangkut, Diolah, Diproses Akhir di TPA/TPST/ SPA Kabupaten/ Kota',
                'satuan' => 'Ton',
            ],
            68 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 64 ',
                'id_kegiatan' => ' 65 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '11',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '04',
                'nomenklatur' => 'Peningkatan Peran Serta Masyarakat dalam Pengelolaan Persampahan',
                'kinerja' => 'Meningkatnya Pemahaman, Kesadaran, Kepedulian, dan Peran Aktif Masyarakat dan Para Pihak Lainnya dalam Pengelolaan Sampah',
                'indikator' => 'Jumlah Masyarakat, Kelompok Masyarakat atau Para Pihak Lairınya yang Terlibat Aktif dalam Kegiatan Pengelolaan Sampah Berbasis Masyarakat',
                'satuan' => 'Kelompok',
            ],
            69 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 64 ',
                'id_kegiatan' => ' 65 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '11',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '05',
                'nomenklatur' => 'Koordinasi dan Sinkronisasi Penyediaan Prasarana dan Sarana Pengelolaan Persampahan',
                'kinerja' => 'Terlaksananya Koordinasi dan Sinkronisasi Penyediaan Prasarana dan Sarana Bersama Pemerintah Pusat, Provinsi maupun Pihak Lain di Luar Kabupaten/Kota nutuk Pengelolaan Sampah Kabupaten/Kota. Pengelolaan Persampahan Sesuai dengan Rencana Induk Pengelolaan Sampah dan Mengacu pada Jakstrada',
                'indikator' => 'Jumlah Dokumen Hasil Koordinasi dan Sinkronisasi Penyediaan Prasarana dan Sarana Bersama Pemerintah Pusat, Provinsi maupun Pihak Lain di Luar Kabupaten/ Kota untuk Pengelolaan Sampah Kabupaten/ Kota. Pengelolaan Persampahan Sesuai dengan Rencana Induk Pengelolaan Sampah dan Mengacu pada Jakstrada',
                'satuan' => 'Dokumen',
            ],
            70 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 64 ',
                'id_kegiatan' => ' 65 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '11',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '06',
                'nomenklatur' => 'Penyusunan Kebijakan Kerja Sanna Pengelolaan Persampahan',
                'kinerja' => 'Terlaksananya Kerja Sama Penanganan Sampah di TPA/TPST Kabupaten/ Kota',
                'indikator' => 'Jumlah Dokumen Kerja Sama Penanganan Sampah di TPA/TPST Kabupaten/ Kota yang Ditetapkan',
                'satuan' => 'Dokumen',
            ],
            71 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 64 ',
                'id_kegiatan' => ' 65 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '11',
                'kode_kegiatan' => '2.01',
                'kode_sub_kegiatan' => '07',
                'nomenklatur' => 'Penyediaan Sarana dan Prasarana Pengelolaan Persampahan di TPA/TPST/ SPA Kabupaten/Kota',
                'kinerja' => 'Tersedianya Sarana dan Prasarana Penanganan Sampah untuk Kegiatan Pemilahan, Pengumpulan, Pengangkutan, Pengolahan, dan Pemrosesan Akhir',
                'indikator' => 'Jumlah Sarana dan Prasarana Penanganan Sampah untuk Kegiatan Pemilahan, Pengumpulan, Pengangkutan, Pengolahan, dan Pemrosesan Akhir',
                'satuan' => 'Unit',
            ],
            72 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 64 ',
                'type' => 'kegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '11',
                'kode_kegiatan' => '2.02',
                'kode_sub_kegiatan' => '',
                'nomenklatur' => 'Penerbitan Izin Pendaurulangan Sampah/Pengelolaan Sampah, Pengangkutan Sampah dan Pemrosesan Akhir Sampah yang Diselenggarakan oleh Swasta',
            ],
            73 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 64 ',
                'id_kegiatan' => ' 73 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '11',
                'kode_kegiatan' => '2.02',
                'kode_sub_kegiatan' => '01',
                'nomenklatur' => 'Pelayanan Perizinan Berusaha Terintegrasi Secara Elektronik',
                'kinerja' => 'Diterbitkannya Rekomendasi Atas Izin/Persetujuan Berusaha Terintegrasi Secara Elektronik Pengelolaan Sampah yang Difasilitasi',
                'indikator' => 'Jumlah Rekomendasi Dari Izin/Persetujuan Berusaha Terintegrasi Secara Elektronik Pengelolaan Sampah yang Difasilitasi',
                'satuan' => 'Rekomendasi',
            ],
            74 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 64 ',
                'type' => 'kegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '11',
                'kode_kegiatan' => '2.03',
                'kode_sub_kegiatan' => '',
                'nomenklatur' => 'Pembinaan dan Pengawasan Pengelolaan Sampah yang Diselenggarakan oleh Pihak Swasta',
            ],
            75 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 64 ',
                'id_kegiatan' => ' 75 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '11',
                'kode_kegiatan' => '2.03',
                'kode_sub_kegiatan' => '01',
                'nomenklatur' => 'Fasilitasi Pemenuhan Ketentuan Terkait Izin Usaha dan Standar Teknis Pengelolaan Sampah',
                'kinerja' => 'Terlaksananya Fasilitasi Pemenuhan Ketentuan Terkait Izin Usaha Dan Standar Teknis Pengelolaan Sampah',
                'indikator' => 'Jumlah Laporan Fasilitasi Pemenuhan Ketentuan Terkait Izin Usaha Dan Standar Teknis Pengelolaan Sampah',
                'satuan' => 'Laporan',
            ],
            76 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 64 ',
                'id_kegiatan' => ' 75 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '11',
                'kode_kegiatan' => '2.03',
                'kode_sub_kegiatan' => '02',
                'nomenklatur' => 'Penyusunan dan Pelaksanaan Penilaian Kinerja Pengelolaan Sampah',
                'kinerja' => 'Terlaksananya Penilaian Kinerja Unit/Usaha/Swasta/Kelompok Masyarakat/Lembaga dalam Pengelolaan Sampah',
                'indikator' => 'Jumlah Unit/Usaha/Swasta/Kelompok Masyarakat/Lembaga dalam Pengelolaan Sampah Melaksanakan Penilaian Kinerja',
                'satuan' => 'Unit',
            ],
            77 => [
                'tahun_anggaran' => '2022',
                'id_program' => ' 64 ',
                'id_kegiatan' => ' 75 ',
                'type' => 'subKegiatan',
                'kode_urusan' => '2',
                'kode_bidang_urusan' => '11',
                'kode_program' => '11',
                'kode_kegiatan' => '2.03',
                'kode_sub_kegiatan' => '03',
                'nomenklatur' => 'Monitoring dan Evaluasi Pemenuhan Target dan Standar Pelayanan Pengelolaan Sampah',
                'kinerja' => 'Monitoring, Evaluasi dan Pelaporan Pemenuhan Target dan Standar Pelayanan Pengelolaan Sampah Kabupaten/Kota yang Dilaksanakan',
                'indikator' => 'Jumlah Laporan Hasil Pelaksanaan Monitoring, Evaluasi dan Pelaporan Pemenuhan Target dan Standar Pelayanan Pengelolaan Sampah Kabupaten /Kota',
                'satuan' => 'Laporan',
            ],
        ];


        foreach ($data as $key => $item) {
            ProgramKegiatan::create($item);
        }
        // KegiatanProgramKegiatan::create
    }
}
